[profile.default]
  solc = "0.8.20"
  bytecode_hash = "none"
  optimizer = true
  optimizer_runs = 1000
  verbosity = 2
  via_ir = true

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[profile.intense.fuzz]
  runs = 1_000

[rpc_endpoints]
  ethereum_mainnet = '${MAINNET_RPC_URL}'

[etherscan]
  mainnet = { key = "${ETHERSCAN_API_KEY}" }

[profile.dev]
  via_ir = false