[profile.default]
solc = "0.8.20"
bytecode_hash = "none"
optimizer_runs = 1000000
verbosity = 2

[profile.intense.fuzz]
runs = 10_000

[rpc_endpoints]
ethereum_mainnet = '${MAINNET_RPC_URL}'

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
