[profile.default]
solc = "0.8.20"
bytecode_hash = "none"
optimizer_runs = 256
verbosity = 2

[profile.intense.fuzz]
runs = 10_000

[rpc_endpoints]
ethereum_mainet = '${MAINET_RPC_URL}'

[etherscan]
polygon = { key = "${ETHERSCAN_API_KEY}" }